# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lm_cpp <- function(X, y, beta, se) {
    invisible(.Call(`_bcb_lm_cpp`, X, y, beta, se))
}

