# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_cpp <- function(X, y, beta) {
    invisible(.Call(`_bcb_beta_cpp`, X, y, beta))
}

lm_cpp <- function(X, y, values) {
    invisible(.Call(`_bcb_lm_cpp`, X, y, values))
}

lm_nig <- function(Xty, m_0, Lambda_0, Lambda_n, V_n, yty, a_n, b_0, beta, se) {
    invisible(.Call(`_bcb_lm_nig`, Xty, m_0, Lambda_0, Lambda_n, V_n, yty, a_n, b_0, beta, se))
}

lm_nig0 <- function(X, y, m_0, Lambda_0, a_0, b_0, n, beta, se) {
    invisible(.Call(`_bcb_lm_nig0`, X, y, m_0, Lambda_0, a_0, b_0, n, beta, se))
}

lookup <- function(parents, ps_i) {
    .Call(`_bcb_lookup`, parents, ps_i)
}

lookup_score_cpp <- function(parents, ps_i, score_col = -1L) {
    .Call(`_bcb_lookup_score_cpp`, parents, ps_i, score_col)
}

